import type { Task, Agent, Epic } from './types'

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    name: 'Claude Code',
    type: 'claude-code',
    avatar: 'CC',
    status: 'idle',
    tasksCompleted: 47,
    successRate: 94,
  },
  {
    id: 'agent-2',
    name: 'Codex CLI',
    type: 'codex',
    avatar: 'CX',
    status: 'busy',
    tasksCompleted: 31,
    successRate: 87,
  },
  {
    id: 'agent-3',
    name: 'Gemini CLI',
    type: 'gemini-cli',
    avatar: 'GC',
    status: 'idle',
    tasksCompleted: 22,
    successRate: 81,
  },
  {
    id: 'agent-4',
    name: 'Custom Agent',
    type: 'custom',
    avatar: 'CA',
    status: 'offline',
    tasksCompleted: 8,
    successRate: 75,
  },
]

export const mockEpics: Epic[] = [
  {
    id: 'epic-1',
    name: 'Аутентификация и авторизация',
    description: 'Полная система аутентификации пользователей с JWT, OAuth, ролями и правами доступа.',
    color: '#f97316',
    status: 'active',
    startDate: Date.now() - 86400000 * 14,
    targetDate: Date.now() + 86400000 * 21,
    createdAt: Date.now() - 86400000 * 14,
    updatedAt: Date.now() - 86400000,
  },
  {
    id: 'epic-2',
    name: 'Инфраструктура и DevOps',
    description: 'Настройка CI/CD, мониторинга, логирования и инфраструктуры для продакшена.',
    color: '#8b5cf6',
    status: 'active',
    startDate: Date.now() - 86400000 * 30,
    targetDate: Date.now() + 86400000 * 10,
    createdAt: Date.now() - 86400000 * 30,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'epic-3',
    name: 'Оптимизация производительности',
    description: 'Профилирование и оптимизация узких мест в базе данных и фронтенде.',
    color: '#ef4444',
    status: 'planning',
    startDate: null,
    targetDate: Date.now() + 86400000 * 45,
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 5,
  },
]

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Реализовать REST API аутентификации',
    description: 'Создать эндпоинты для регистрации, логина и обновления токена с JWT.',
    prompt: 'Реализуй REST API для аутентификации пользователей с использованием JWT. Эндпоинты: POST /auth/register, POST /auth/login, POST /auth/refresh. Используй bcrypt для хеширования паролей.',
    status: 'backlog',
    priority: 'high',
    assignedAgent: null,
    epicId: 'epic-1',
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 3,
    deadline: Date.now() + 86400000 * 5,
    estimatedTime: 45,
    progress: 0,
    logs: [],
    review: null,
    tags: ['backend', 'auth', 'api'],
    subtasks: [
      { id: 'st-1', title: 'Создать модель User', done: false },
      { id: 'st-2', title: 'Реализовать JWT middleware', done: false },
      { id: 'st-3', title: 'Написать эндпоинты', done: false },
    ],
    comments: [],
    color: '#f97316',
  },
  {
    id: 'task-2',
    title: 'Написать unit-тесты для сервиса пользователей',
    description: 'Покрыть тестами основные методы UserService: create, findById, update, delete.',
    prompt: 'Напиши unit-тесты для UserService. Используй Jest и моки для зависимостей. Покрой крайние случаи: несуществующий пользователь, дублирующий email, невалидные данные.',
    status: 'backlog',
    priority: 'medium',
    assignedAgent: null,
    epicId: 'epic-1',
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
    deadline: null,
    estimatedTime: 30,
    progress: 0,
    logs: [],
    review: null,
    tags: ['testing', 'backend'],
    subtasks: [],
    comments: [
      { id: 'c-1', author: 'Администратор', text: 'Не забыть про edge cases с null полями', timestamp: Date.now() - 86400000 },
    ],
    color: '#3b82f6',
  },
  {
    id: 'task-3',
    title: 'Оптимизировать SQL запросы в дашборде',
    description: 'Профилировать и оптимизировать медленные запросы на странице аналитики.',
    prompt: 'Проанализируй SQL запросы в модуле аналитики. Добавь недостающие индексы, оптимизируй JOIN-ы, используй материализованные представления где это оправдано.',
    status: 'in_progress',
    priority: 'critical',
    assignedAgent: 'agent-1',
    epicId: 'epic-3',
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 3600000,
    deadline: Date.now() + 86400000 * 2,
    estimatedTime: 60,
    progress: 65,
    logs: [
      { timestamp: Date.now() - 7200000, message: 'Начат анализ запросов...', type: 'info' },
      { timestamp: Date.now() - 5400000, message: 'Найдено 3 запроса без индексов', type: 'warning' },
      { timestamp: Date.now() - 3600000, message: 'Оптимизирован запрос dashboard_stats — ускорение x4', type: 'success' },
    ],
    review: null,
    tags: ['database', 'performance'],
    subtasks: [
      { id: 'st-4', title: 'Профилировать запросы', done: true },
      { id: 'st-5', title: 'Добавить индексы', done: true },
      { id: 'st-6', title: 'Оптимизировать JOIN-ы', done: false },
    ],
    comments: [],
    color: '#ef4444',
  },
  {
    id: 'task-4',
    title: 'Рефакторинг компонента таблицы данных',
    description: 'Переписать DataTable на основе TanStack Table с поддержкой сортировки и фильтрации.',
    prompt: 'Рефакторни компонент DataTable. Используй @tanstack/react-table v8. Добавь: серверную сортировку, фильтрацию по колонкам, пагинацию, выбор строк.',
    status: 'in_progress',
    priority: 'medium',
    assignedAgent: 'agent-2',
    epicId: null,
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 1800000,
    deadline: Date.now() + 86400000 * 7,
    estimatedTime: 90,
    progress: 35,
    logs: [
      { timestamp: Date.now() - 3600000, message: 'Создана базовая структура таблицы', type: 'info' },
      { timestamp: Date.now() - 1800000, message: 'Реализована сортировка по колонкам', type: 'success' },
    ],
    review: null,
    tags: ['frontend', 'refactoring'],
    subtasks: [],
    comments: [],
    color: '#8b5cf6',
  },
  {
    id: 'task-5',
    title: 'Настроить CI/CD пайплайн',
    description: 'Создать GitHub Actions workflow для автоматического тестирования и деплоя.',
    prompt: 'Настрой CI/CD пайплайн через GitHub Actions. Шаги: lint, test, build, deploy (staging при push в develop, production при push в main).',
    status: 'review',
    priority: 'high',
    assignedAgent: 'agent-1',
    epicId: 'epic-2',
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 7200000,
    deadline: null,
    estimatedTime: 40,
    progress: 100,
    logs: [
      { timestamp: Date.now() - 86400000, message: 'Workflow файл создан', type: 'info' },
      { timestamp: Date.now() - 43200000, message: 'Тесты проходят в CI', type: 'success' },
      { timestamp: Date.now() - 7200000, message: 'Деплой на staging выполнен успешно', type: 'success' },
    ],
    review: {
      reviewer: 'Александр К.',
      score: 8,
      comment: 'Хороший пайплайн, но стоит добавить кэширование зависимостей.',
      timestamp: Date.now() - 3600000,
    },
    tags: ['devops', 'ci-cd'],
    subtasks: [],
    comments: [],
    color: '#f97316',
  },
  {
    id: 'task-6',
    title: 'Добавить WebSocket уведомления',
    description: 'Реализовать real-time уведомления о статусе задач через WebSocket.',
    prompt: 'Реализуй WebSocket сервер для real-time уведомлений. События: task_started, task_progress, task_completed, task_failed. Используй Socket.IO.',
    status: 'done',
    priority: 'medium',
    assignedAgent: 'agent-3',
    epicId: 'epic-2',
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 2,
    deadline: null,
    estimatedTime: 55,
    progress: 100,
    logs: [
      { timestamp: Date.now() - 86400000 * 5, message: 'Сервер WebSocket запущен', type: 'info' },
      { timestamp: Date.now() - 86400000 * 4, message: 'Подключены обработчики событий', type: 'success' },
      { timestamp: Date.now() - 86400000 * 2, message: 'Задача завершена', type: 'success' },
    ],
    review: {
      reviewer: 'Мария С.',
      score: 9,
      comment: 'Отличная реализация, чистый код.',
      timestamp: Date.now() - 86400000,
    },
    tags: ['backend', 'realtime'],
    subtasks: [],
    comments: [],
    color: '#22c55e',
  },
]
