import type { Task, Agent, Epic, User } from './types'

const DAY = 86400000

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Администратор',
    email: 'admin@llmkanban.ru',
    role: 'admin',
    avatar: 'АД',
    bio: 'Главный администратор системы оркестрации LLM-агентов. Отвечает за конфигурацию пайплайнов и мониторинг.',
    position: 'DevOps Lead',
    joinedAt: Date.now() - DAY * 120,
  },
  {
    id: 'user-2',
    name: 'Александр Козлов',
    email: 'a.kozlov@llmkanban.ru',
    role: 'developer',
    avatar: 'АК',
    bio: 'Backend-разработчик, специализируюсь на оптимизации SQL и построении REST API. Опыт работы с Claude Code и Codex.',
    position: 'Senior Backend Developer',
    joinedAt: Date.now() - DAY * 90,
  },
  {
    id: 'user-3',
    name: 'Мария Сидорова',
    email: 'm.sidorova@llmkanban.ru',
    role: 'developer',
    avatar: 'МС',
    bio: 'Frontend-разработчик. React, TypeScript, дизайн-системы. Провожу ревью результатов LLM-агентов.',
    position: 'Frontend Developer',
    joinedAt: Date.now() - DAY * 60,
  },
  {
    id: 'user-4',
    name: 'Дмитрий Волков',
    email: 'd.volkov@llmkanban.ru',
    role: 'manager',
    avatar: 'ДВ',
    bio: 'Технический менеджер проекта. Координирую работу команды и распределение задач по агентам.',
    position: 'Technical Project Manager',
    joinedAt: Date.now() - DAY * 110,
  },
  {
    id: 'user-5',
    name: 'Елена Новикова',
    email: 'e.novikova@llmkanban.ru',
    role: 'developer',
    avatar: 'ЕН',
    bio: 'QA-инженер. Пишу автотесты и проверяю результаты работы LLM-агентов перед деплоем.',
    position: 'QA Engineer',
    joinedAt: Date.now() - DAY * 45,
  },
]

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    name: 'Claude Code',
    type: 'claude-code',
    avatar: 'CC',
    status: 'idle',
    tasksCompleted: 47,
    successRate: 94,
    description: 'Основной агент для генерации и рефакторинга кода. Отлично справляется с TypeScript, Python, SQL. Поддерживает сложные мультифайловые изменения.',
    avgExecutionTime: 12,
    config: { model: 'claude-sonnet-4-20250514', maxTokens: 16384, temperature: 0 },
    createdAt: Date.now() - DAY * 100,
  },
  {
    id: 'agent-2',
    name: 'Codex CLI',
    type: 'codex',
    avatar: 'CX',
    status: 'busy',
    tasksCompleted: 31,
    successRate: 87,
    description: 'Агент OpenAI для кодогенерации. Хорош для быстрых задач и прототипирования. Менее точен в больших рефакторингах.',
    avgExecutionTime: 8,
    config: { model: 'o3-mini', maxTokens: 8192, temperature: 0.2 },
    createdAt: Date.now() - DAY * 80,
  },
  {
    id: 'agent-3',
    name: 'Gemini CLI',
    type: 'gemini-cli',
    avatar: 'GC',
    status: 'idle',
    tasksCompleted: 22,
    successRate: 81,
    description: 'Google Gemini агент. Сильная сторона — работа с документацией, генерация тестов и анализ кода.',
    avgExecutionTime: 15,
    config: { model: 'gemini-2.5-pro', maxTokens: 32768, temperature: 0.1 },
    createdAt: Date.now() - DAY * 50,
  },
  {
    id: 'agent-4',
    name: 'Custom Agent',
    type: 'custom',
    avatar: 'CA',
    status: 'offline',
    tasksCompleted: 8,
    successRate: 75,
    description: 'Экспериментальный агент с кастомным пайплайном. Используется для специфических задач, требующих нестандартного подхода.',
    avgExecutionTime: 25,
    config: { model: 'llama-3.1-70b', maxTokens: 4096, temperature: 0.3 },
    createdAt: Date.now() - DAY * 20,
  },
]

export const mockEpics: Epic[] = [
  {
    id: 'epic-1',
    name: 'Аутентификация и авторизация',
    description: 'Полная система аутентификации пользователей с JWT, OAuth, ролями и правами доступа. Включает двухфакторную аутентификацию и интеграцию с SSO.',
    icon: 'lock',
    color: '#f97316',
    status: 'active',
    startDate: Date.now() - DAY * 14,
    targetDate: Date.now() + DAY * 21,
    createdAt: Date.now() - DAY * 14,
    updatedAt: Date.now() - DAY,
  },
  {
    id: 'epic-2',
    name: 'Инфраструктура и DevOps',
    description: 'Настройка CI/CD, мониторинга, логирования и инфраструктуры для продакшена. Docker, Kubernetes, автоскейлинг.',
    icon: 'rocket',
    color: '#8b5cf6',
    status: 'active',
    startDate: Date.now() - DAY * 30,
    targetDate: Date.now() + DAY * 10,
    createdAt: Date.now() - DAY * 30,
    updatedAt: Date.now() - DAY * 2,
  },
  {
    id: 'epic-3',
    name: 'Оптимизация производительности',
    description: 'Профилирование и оптимизация узких мест в базе данных и фронтенде. Кэширование, lazy loading, оптимизация запросов.',
    icon: 'bolt',
    color: '#ef4444',
    status: 'planning',
    startDate: null,
    targetDate: Date.now() + DAY * 45,
    createdAt: Date.now() - DAY * 7,
    updatedAt: Date.now() - DAY * 5,
  },
  {
    id: 'epic-4',
    name: 'API для мобильного приложения',
    description: 'Разработка REST и GraphQL API для мобильного клиента. Оптимизация для слабых соединений, пагинация, WebSocket для реального времени.',
    icon: 'smartphone',
    color: '#3b82f6',
    status: 'active',
    startDate: Date.now() - DAY * 10,
    targetDate: Date.now() + DAY * 35,
    createdAt: Date.now() - DAY * 10,
    updatedAt: Date.now() - DAY * 3,
  },
  {
    id: 'epic-5',
    name: 'Система уведомлений',
    description: 'Email, push и in-app уведомления. Настраиваемые правила, шаблоны, дайджесты. Интеграция со Slack и Telegram.',
    icon: 'bell',
    color: '#eab308',
    status: 'planning',
    startDate: null,
    targetDate: Date.now() + DAY * 60,
    createdAt: Date.now() - DAY * 5,
    updatedAt: Date.now() - DAY * 5,
  },
  {
    id: 'epic-6',
    name: 'Документация и онбординг',
    description: 'Автогенерация документации API, интерактивные гайды для новых пользователей, база знаний.',
    icon: 'book-open',
    color: '#14b8a6',
    status: 'completed',
    startDate: Date.now() - DAY * 60,
    targetDate: Date.now() - DAY * 5,
    createdAt: Date.now() - DAY * 60,
    updatedAt: Date.now() - DAY * 5,
  },
]

export const mockTasks: Task[] = [
  // ── Epic 1: Auth ──
  {
    id: 'task-1',
    title: 'Реализовать REST API аутентификации',
    description: 'Создать эндпоинты для регистрации, логина и обновления токена с JWT.',
    prompt: 'Реализуй REST API для аутентификации пользователей с использованием JWT. Эндпоинты: POST /auth/register, POST /auth/login, POST /auth/refresh. Используй bcrypt для хеширования паролей.',
    status: 'prompt_ready',
    priority: 'high',
    assignedAgent: null,
    createdBy: 'user-2',
    epicId: 'epic-1',
    createdAt: Date.now() - DAY * 3,
    updatedAt: Date.now() - DAY * 3,
    deadline: Date.now() + DAY * 5,
    estimatedTime: 45,
    progress: 0,
    logs: [],
    review: null,
    tags: ['backend', 'auth', 'api'],
    subtasks: [
      { id: 'st-1', title: 'Создать модель User', done: false },
      { id: 'st-2', title: 'Реализовать JWT middleware', done: false },
      { id: 'st-3', title: 'Написать эндпоинты', done: false },
    ],
    comments: [],
    color: '#f97316',
  },
  {
    id: 'task-2',
    title: 'Написать unit-тесты для сервиса пользователей',
    description: 'Покрыть тестами основные методы UserService: create, findById, update, delete.',
    prompt: 'Напиши unit-тесты для UserService. Используй Jest и моки для зависимостей. Покрой крайние случаи: несуществующий пользователь, дублирующий email, невалидные данные.',
    status: 'backlog',
    priority: 'medium',
    assignedAgent: null,
    createdBy: 'user-5',
    epicId: 'epic-1',
    createdAt: Date.now() - DAY * 2,
    updatedAt: Date.now() - DAY * 2,
    deadline: null,
    estimatedTime: 30,
    progress: 0,
    logs: [],
    review: null,
    tags: ['testing', 'backend'],
    subtasks: [],
    comments: [
      { id: 'c-1', author: 'Елена Новикова', text: 'Не забыть про edge cases с null полями', timestamp: Date.now() - DAY },
    ],
    color: '#3b82f6',
  },
  {
    id: 'task-10',
    title: 'Реализовать OAuth2 авторизацию через Google',
    description: 'Добавить возможность входа через Google OAuth2. Интеграция с passport.js.',
    prompt: 'Реализуй авторизацию через Google OAuth2 используя passport.js. Настрой стратегию, обработчики callback, создание/привязку аккаунта при первом входе.',
    status: 'agent_assigned',
    priority: 'high',
    assignedAgent: 'agent-1',
    createdBy: 'user-4',
    epicId: 'epic-1',
    createdAt: Date.now() - DAY * 6,
    updatedAt: Date.now() - DAY,
    deadline: Date.now() + DAY * 10,
    estimatedTime: 60,
    progress: 0,
    logs: [],
    review: null,
    tags: ['backend', 'auth', 'oauth'],
    subtasks: [
      { id: 'st-10', title: 'Настроить Google Developer Console', done: true },
      { id: 'st-11', title: 'Реализовать passport strategy', done: false },
      { id: 'st-12', title: 'Создать callback endpoint', done: false },
    ],
    comments: [
      { id: 'c-10', author: 'Дмитрий Волков', text: 'Используем passport.js как стандарт для всех OAuth провайдеров', timestamp: Date.now() - DAY * 2 },
    ],
    color: '#f97316',
  },
  // ── Epic 2: DevOps ──
  {
    id: 'task-5',
    title: 'Настроить CI/CD пайплайн',
    description: 'Создать GitHub Actions workflow для автоматического тестирования и деплоя.',
    prompt: 'Настрой CI/CD пайплайн через GitHub Actions. Шаги: lint, test, build, deploy (staging при push в develop, production при push в main).',
    status: 'review',
    priority: 'high',
    assignedAgent: 'agent-1',
    createdBy: 'user-1',
    epicId: 'epic-2',
    createdAt: Date.now() - DAY * 7,
    updatedAt: Date.now() - 7200000,
    deadline: null,
    estimatedTime: 40,
    progress: 100,
    logs: [
      { timestamp: Date.now() - DAY, message: 'Workflow файл создан', type: 'info' },
      { timestamp: Date.now() - 43200000, message: 'Тесты проходят в CI', type: 'success' },
      { timestamp: Date.now() - 7200000, message: 'Деплой на staging выполнен успешно', type: 'success' },
    ],
    review: {
      reviewer: 'Александр К.',
      score: 8,
      comment: 'Хороший пайплайн, но стоит добавить кэширование зависимостей.',
      timestamp: Date.now() - 3600000,
    },
    tags: ['devops', 'ci-cd'],
    subtasks: [],
    comments: [],
    color: '#8b5cf6',
    pipelines: [
      {
        id: 'pl-1',
        runNumber: 1,
        branch: 'feature/ci-cd',
        commit: 'a3f8c2d',
        status: 'success',
        stages: [
          { id: 'lint', name: 'Lint', status: 'success', needs: [], startedAt: Date.now() - DAY * 2, finishedAt: Date.now() - DAY * 2 + 30000, log: 'eslint: 0 errors, 0 warnings' },
          { id: 'typecheck', name: 'Typecheck', status: 'success', needs: [], startedAt: Date.now() - DAY * 2, finishedAt: Date.now() - DAY * 2 + 45000, log: 'tsc --noEmit: OK' },
          { id: 'build', name: 'Build', status: 'success', needs: ['lint', 'typecheck'], startedAt: Date.now() - DAY * 2 + 45000, finishedAt: Date.now() - DAY * 2 + 90000, log: 'vite build: 2.1 MB' },
          { id: 'unit-test', name: 'Unit Tests', status: 'success', needs: ['build'], startedAt: Date.now() - DAY * 2 + 90000, finishedAt: Date.now() - DAY * 2 + 150000, log: '142/142 passed' },
          { id: 'e2e-test', name: 'E2E Tests', status: 'success', needs: ['build'], startedAt: Date.now() - DAY * 2 + 90000, finishedAt: Date.now() - DAY * 2 + 200000, log: '38/38 passed (Playwright)' },
          { id: 'security', name: 'Security Scan', status: 'success', needs: ['build'], startedAt: Date.now() - DAY * 2 + 90000, finishedAt: Date.now() - DAY * 2 + 130000, log: '0 vulnerabilities found' },
          { id: 'deploy-staging', name: 'Deploy Staging', status: 'success', needs: ['unit-test', 'e2e-test', 'security'], startedAt: Date.now() - DAY * 2 + 200000, finishedAt: Date.now() - DAY * 2 + 260000, log: 'Deployed to k8s-staging' },
          { id: 'deploy-prod', name: 'Deploy Prod', status: 'success', needs: ['deploy-staging'], startedAt: Date.now() - DAY * 2 + 260000, finishedAt: Date.now() - DAY * 2 + 320000, log: 'Deployed to k8s-prod' },
        ],
        triggeredAt: Date.now() - DAY * 2,
        url: '#',
      },
      {
        id: 'pl-2',
        runNumber: 2,
        branch: 'main',
        commit: 'e7b1f09',
        status: 'failed',
        stages: [
          { id: 'lint', name: 'Lint', status: 'success', needs: [], startedAt: Date.now() - DAY, finishedAt: Date.now() - DAY + 28000, log: 'eslint: 0 errors' },
          { id: 'typecheck', name: 'Typecheck', status: 'success', needs: [], startedAt: Date.now() - DAY, finishedAt: Date.now() - DAY + 40000, log: 'tsc: OK' },
          { id: 'build', name: 'Build', status: 'success', needs: ['lint', 'typecheck'], startedAt: Date.now() - DAY + 40000, finishedAt: Date.now() - DAY + 85000, log: 'vite build: 2.1 MB' },
          { id: 'unit-test', name: 'Unit Tests', status: 'failed', needs: ['build'], startedAt: Date.now() - DAY + 85000, finishedAt: Date.now() - DAY + 160000, log: 'FAIL: 2 of 142 tests failed' },
          { id: 'e2e-test', name: 'E2E Tests', status: 'success', needs: ['build'], startedAt: Date.now() - DAY + 85000, finishedAt: Date.now() - DAY + 190000, log: '38/38 passed' },
          { id: 'security', name: 'Security Scan', status: 'success', needs: ['build'], startedAt: Date.now() - DAY + 85000, finishedAt: Date.now() - DAY + 120000, log: '0 vulnerabilities' },
          { id: 'deploy-staging', name: 'Deploy Staging', status: 'skipped', needs: ['unit-test', 'e2e-test', 'security'], startedAt: null, finishedAt: null, log: '' },
          { id: 'deploy-prod', name: 'Deploy Prod', status: 'skipped', needs: ['deploy-staging'], startedAt: null, finishedAt: null, log: '' },
        ],
        triggeredAt: Date.now() - DAY,
        url: '#',
      },
    ],
    attachments: [
      { id: 'att-1', type: 'link', name: 'GitHub Actions Docs', url: 'https://docs.github.com/en/actions', addedAt: Date.now() - DAY * 5, addedBy: 'Администратор' },
      { id: 'att-2', type: 'link', name: 'Jira задача DEV-142', url: 'https://jira.example.com/DEV-142', addedAt: Date.now() - DAY * 4, addedBy: 'Дмитрий Волков' },
    ],
  },
  {
    id: 'task-6',
    title: 'Добавить WebSocket уведомления',
    description: 'Реализовать real-time уведомления о статусе задач через WebSocket.',
    prompt: 'Реализуй WebSocket сервер для real-time уведомлений. События: task_started, task_progress, task_completed, task_failed. Используй Socket.IO.',
    status: 'done',
    priority: 'medium',
    assignedAgent: 'agent-3',
    createdBy: 'user-3',
    epicId: 'epic-2',
    createdAt: Date.now() - DAY * 10,
    updatedAt: Date.now() - DAY * 2,
    deadline: null,
    estimatedTime: 55,
    progress: 100,
    logs: [
      { timestamp: Date.now() - DAY * 5, message: 'Сервер WebSocket запущен', type: 'info' },
      { timestamp: Date.now() - DAY * 4, message: 'Подключены обработчики событий', type: 'success' },
      { timestamp: Date.now() - DAY * 2, message: 'Задача завершена', type: 'success' },
    ],
    review: {
      reviewer: 'Мария С.',
      score: 9,
      comment: 'Отличная реализация, чистый код.',
      timestamp: Date.now() - DAY,
    },
    tags: ['backend', 'realtime'],
    subtasks: [],
    comments: [],
    color: '#22c55e',
  },
  {
    id: 'task-11',
    title: 'Настроить мониторинг с Grafana + Prometheus',
    description: 'Развернуть стек мониторинга: сбор метрик, дашборды, алерты.',
    prompt: 'Настрой мониторинг приложения. Используй Prometheus для сбора метрик (HTTP latency, error rate, memory usage) и Grafana для визуализации. Настрой алерты в Slack при превышении пороговых значений.',
    status: 'executing',
    priority: 'medium',
    assignedAgent: 'agent-2',
    createdBy: 'user-1',
    epicId: 'epic-2',
    createdAt: Date.now() - DAY * 4,
    updatedAt: Date.now() - 1800000,
    deadline: Date.now() + DAY * 7,
    estimatedTime: 90,
    progress: 45,
    logs: [
      { timestamp: Date.now() - DAY * 2, message: 'Docker compose для Prometheus/Grafana создан', type: 'info' },
      { timestamp: Date.now() - DAY, message: 'Метрики приложения экспортируются', type: 'success' },
      { timestamp: Date.now() - 1800000, message: 'Создание дашбордов...', type: 'info' },
    ],
    review: null,
    tags: ['devops', 'monitoring'],
    subtasks: [
      { id: 'st-20', title: 'Docker compose', done: true },
      { id: 'st-21', title: 'Экспорт метрик', done: true },
      { id: 'st-22', title: 'Дашборды Grafana', done: false },
      { id: 'st-23', title: 'Алерты в Slack', done: false },
    ],
    comments: [],
    color: '#8b5cf6',
  },
  // ── Epic 3: Performance ──
  {
    id: 'task-3',
    title: 'Оптимизировать SQL запросы в дашборде',
    description: 'Профилировать и оптимизировать медленные запросы на странице аналитики.',
    prompt: 'Проанализируй SQL запросы в модуле аналитики. Добавь недостающие индексы, оптимизируй JOIN-ы, используй материализованные представления где это оправдано.',
    status: 'executing',
    priority: 'critical',
    assignedAgent: 'agent-1',
    createdBy: 'user-2',
    epicId: 'epic-3',
    createdAt: Date.now() - DAY * 5,
    updatedAt: Date.now() - 3600000,
    deadline: Date.now() + DAY * 2,
    estimatedTime: 60,
    progress: 65,
    logs: [
      { timestamp: Date.now() - 7200000, message: 'Начат анализ запросов...', type: 'info' },
      { timestamp: Date.now() - 5400000, message: 'Найдено 3 запроса без индексов', type: 'warning' },
      { timestamp: Date.now() - 3600000, message: 'Оптимизирован запрос dashboard_stats — ускорение x4', type: 'success' },
    ],
    review: null,
    tags: ['database', 'performance'],
    subtasks: [
      { id: 'st-4', title: 'Профилировать запросы', done: true },
      { id: 'st-5', title: 'Добавить индексы', done: true },
      { id: 'st-6', title: 'Оптимизировать JOIN-ы', done: false },
    ],
    comments: [
      { id: 'c-3', author: 'Александр Козлов', text: 'Запрос dashboard_stats теперь работает за 120ms вместо 480ms', timestamp: Date.now() - 3600000 },
    ],
    color: '#ef4444',
  },
  // ── Epic 4: Mobile API ──
  {
    id: 'task-4',
    title: 'Рефакторинг компонента таблицы данных',
    description: 'Переписать DataTable на основе TanStack Table с поддержкой сортировки и фильтрации.',
    prompt: 'Рефакторни компонент DataTable. Используй @tanstack/react-table v8. Добавь: серверную сортировку, фильтрацию по колонкам, пагинацию, выбор строк.',
    status: 'executing',
    priority: 'medium',
    assignedAgent: 'agent-2',
    createdBy: 'user-3',
    epicId: 'epic-4',
    createdAt: Date.now() - DAY * 4,
    updatedAt: Date.now() - 1800000,
    deadline: Date.now() + DAY * 7,
    estimatedTime: 90,
    progress: 35,
    logs: [
      { timestamp: Date.now() - 3600000, message: 'Создана базовая структура таблицы', type: 'info' },
      { timestamp: Date.now() - 1800000, message: 'Реализована сортировка по колонкам', type: 'success' },
    ],
    review: null,
    tags: ['frontend', 'refactoring'],
    subtasks: [],
    comments: [],
    color: '#3b82f6',
  },
  {
    id: 'task-12',
    title: 'Разработать GraphQL схему для мобильного клиента',
    description: 'Определить типы, queries и mutations для мобильного приложения.',
    prompt: 'Создай GraphQL схему для мобильного клиента. Типы: User, Task, Epic, Agent. Queries: tasks(filter, pagination), epics, agents. Mutations: createTask, updateTask, moveTask. Используй Apollo Server.',
    status: 'prompt_ready',
    priority: 'high',
    assignedAgent: null,
    createdBy: 'user-4',
    epicId: 'epic-4',
    createdAt: Date.now() - DAY * 3,
    updatedAt: Date.now() - DAY * 3,
    deadline: Date.now() + DAY * 14,
    estimatedTime: 50,
    progress: 0,
    logs: [],
    review: null,
    tags: ['backend', 'graphql', 'mobile'],
    subtasks: [
      { id: 'st-30', title: 'Определить типы', done: false },
      { id: 'st-31', title: 'Реализовать resolvers', done: false },
      { id: 'st-32', title: 'Настроить Apollo Server', done: false },
    ],
    comments: [],
    color: '#3b82f6',
  },
  {
    id: 'task-13',
    title: 'Реализовать пагинацию для REST API',
    description: 'Cursor-based пагинация для списков задач и эпиков.',
    prompt: 'Реализуй cursor-based пагинацию для эндпоинтов GET /tasks и GET /epics. Параметры: cursor, limit, sort. Верни структуру { data, nextCursor, hasMore }.',
    status: 'done',
    priority: 'medium',
    assignedAgent: 'agent-1',
    createdBy: 'user-2',
    epicId: 'epic-4',
    createdAt: Date.now() - DAY * 8,
    updatedAt: Date.now() - DAY * 3,
    deadline: null,
    estimatedTime: 35,
    progress: 100,
    logs: [
      { timestamp: Date.now() - DAY * 5, message: 'Реализован cursor-based pagination', type: 'info' },
      { timestamp: Date.now() - DAY * 4, message: 'Тесты пройдены', type: 'success' },
      { timestamp: Date.now() - DAY * 3, message: 'Задача завершена', type: 'success' },
    ],
    review: {
      reviewer: 'Александр К.',
      score: 9,
      comment: 'Чистая реализация, хорошая обработка edge cases.',
      timestamp: Date.now() - DAY * 3,
    },
    tags: ['backend', 'api'],
    subtasks: [],
    comments: [],
    color: '#3b82f6',
  },
  // ── Epic 5: Notifications ──
  {
    id: 'task-14',
    title: 'Спроектировать систему шаблонов уведомлений',
    description: 'Создать движок шаблонов для email, push и in-app уведомлений с поддержкой переменных.',
    prompt: 'Спроектируй и реализуй систему шаблонов уведомлений. Шаблоны должны поддерживать: переменные ({{user.name}}), условия (if/else), локализацию. Храни шаблоны в БД, кэшируй в Redis.',
    status: 'backlog',
    priority: 'medium',
    assignedAgent: null,
    createdBy: 'user-4',
    epicId: 'epic-5',
    createdAt: Date.now() - DAY * 2,
    updatedAt: Date.now() - DAY * 2,
    deadline: null,
    estimatedTime: 70,
    progress: 0,
    logs: [],
    review: null,
    tags: ['backend', 'notifications', 'templates'],
    subtasks: [],
    comments: [
      { id: 'c-14', author: 'Дмитрий Волков', text: 'Посмотри на Handlebars или Mustache как reference', timestamp: Date.now() - DAY },
    ],
    color: '#eab308',
  },
  {
    id: 'task-15',
    title: 'Интеграция уведомлений со Slack',
    description: 'Отправка уведомлений о статусе задач в Slack через Incoming Webhooks.',
    prompt: 'Реализуй отправку уведомлений в Slack через Incoming Webhooks. События: задача создана, статус изменён, ревью завершено, задача провалена. Форматируй сообщения с Slack Block Kit.',
    status: 'backlog',
    priority: 'low',
    assignedAgent: null,
    createdBy: 'user-1',
    epicId: 'epic-5',
    createdAt: Date.now() - DAY,
    updatedAt: Date.now() - DAY,
    deadline: null,
    estimatedTime: 40,
    progress: 0,
    logs: [],
    review: null,
    tags: ['backend', 'integrations', 'slack'],
    subtasks: [],
    comments: [],
    color: '#eab308',
  },
  // ── Epic 6: Docs (completed) ──
  {
    id: 'task-16',
    title: 'Автогенерация OpenAPI документации',
    description: 'Настроить swagger-jsdoc для автоматической генерации OpenAPI спецификации.',
    prompt: 'Настрой автогенерацию OpenAPI документации из JSDoc комментариев. Используй swagger-jsdoc + swagger-ui-express. Документируй все эндпоинты с примерами запросов/ответов.',
    status: 'done',
    priority: 'medium',
    assignedAgent: 'agent-3',
    createdBy: 'user-3',
    epicId: 'epic-6',
    createdAt: Date.now() - DAY * 40,
    updatedAt: Date.now() - DAY * 10,
    deadline: null,
    estimatedTime: 30,
    progress: 100,
    logs: [
      { timestamp: Date.now() - DAY * 20, message: 'swagger-jsdoc настроен', type: 'info' },
      { timestamp: Date.now() - DAY * 15, message: 'Все эндпоинты документированы', type: 'success' },
      { timestamp: Date.now() - DAY * 10, message: 'Задача завершена', type: 'success' },
    ],
    review: { reviewer: 'Мария С.', score: 10, comment: 'Идеальная документация!', timestamp: Date.now() - DAY * 10 },
    tags: ['docs', 'api'],
    subtasks: [],
    comments: [],
    color: '#14b8a6',
  },
  // ── No epic ──
  {
    id: 'task-17',
    title: 'Исправить утечку памяти в WebSocket handler',
    description: 'При отключении клиента не очищаются event listeners, что приводит к утечке памяти.',
    prompt: 'Найди и исправь утечку памяти в WebSocket handler. Проблема: при отключении клиента event listeners не удаляются. Используй WeakMap для хранения ссылок и cleanup функции.',
    status: 'rework',
    priority: 'critical',
    assignedAgent: 'agent-1',
    createdBy: 'user-2',
    epicId: null,
    createdAt: Date.now() - DAY * 3,
    updatedAt: Date.now() - DAY,
    deadline: Date.now() + DAY,
    estimatedTime: 25,
    progress: 70,
    logs: [
      { timestamp: Date.now() - DAY * 2, message: 'Начат анализ утечки...', type: 'info' },
      { timestamp: Date.now() - DAY * 2 + 3600000, message: 'Обнаружен незакрытый listener на событие message', type: 'warning' },
      { timestamp: Date.now() - DAY, message: 'Исправление не полное — найдена ещё одна утечка в heartbeat', type: 'error' },
    ],
    review: null,
    tags: ['bugfix', 'backend', 'websocket'],
    subtasks: [
      { id: 'st-40', title: 'Исправить message listener', done: true },
      { id: 'st-41', title: 'Исправить heartbeat cleanup', done: false },
      { id: 'st-42', title: 'Добавить тест на утечки', done: false },
    ],
    comments: [
      { id: 'c-17', author: 'Александр Козлов', text: 'Heap snapshot показывает рост на ~2MB/час при 100 соединениях', timestamp: Date.now() - DAY * 2 },
      { id: 'c-18', author: 'Елена Новикова', text: 'Нужен нагрузочный тест после фикса', timestamp: Date.now() - DAY },
    ],
    color: '#ef4444',
  },
  {
    id: 'task-18',
    title: 'Добавить rate limiting для API',
    description: 'Защита API от DDoS и abuse через ограничение частоты запросов.',
    prompt: 'Реализуй rate limiting для REST API. Используй express-rate-limit с Redis store. Лимиты: 100 req/min для обычных, 20 req/min для auth эндпоинтов. Верни заголовки X-RateLimit-*.',
    status: 'review',
    priority: 'high',
    assignedAgent: 'agent-2',
    createdBy: 'user-1',
    epicId: null,
    createdAt: Date.now() - DAY * 6,
    updatedAt: Date.now() - DAY,
    deadline: null,
    estimatedTime: 35,
    progress: 100,
    logs: [
      { timestamp: Date.now() - DAY * 3, message: 'express-rate-limit настроен', type: 'info' },
      { timestamp: Date.now() - DAY * 2, message: 'Redis store подключен', type: 'success' },
      { timestamp: Date.now() - DAY, message: 'Задача завершена', type: 'success' },
    ],
    review: {
      reviewer: 'Елена Н.',
      score: 7,
      comment: 'Работает, но нужно добавить whitelist для внутренних сервисов.',
      timestamp: Date.now() - 3600000 * 6,
    },
    tags: ['backend', 'security'],
    subtasks: [],
    comments: [],
    color: '#64748b',
  },
]
